### ISSUE TITLE
Can't install app on Apple TV 4

### ISSUE THREAD

**Issue by ADMNTK** [Kinglilrowrow/PopcornTimeTV#1]
Hi

After extracting the application from the project, app and create a new folder named Payload and put the app inside it and compress the file and convert it to ipa
And the installation of the app by itools , ifunbox unfortunately shows failed

Version of the app in the project: iOS11
Version of the Apple TV 4 : iOS11

Please solve this problem

 Thank you.

**Comment by Kinglilrowrow** [comment]
You install with Xcode, and requires tvOS 11.1 or above. 

Use Xcode, sign in with either a developer account or a standard account and run the Xcode build and set your Apple TV 4 as the target.

**Comment by sqig** [comment]
Hello,
working great for me me on both Apple TV4 and 4K.
Looking forward to the 4K torrents.
Keep up the good work.
Thank you.

**Comment by tibtiby** [comment]
Could someone please walk me through on how to install this on my Apple TV 4, tvos11? I can't seem to manage to install it via XCode.

**Comment by Kinglilrowrow** [comment]
@tibtiby and @ADMNTK see here: https://github.com/Kinglilrowrow/PopcornTimeTV/wiki/PopcornTime-Build-Instructions.

For the Wiki I've create with full install instructions. 

This issue will now be closed.
