### ISSUE TITLE
PopcornTime

### ISSUE THREAD

**Issue by sqig** [Kinglilrowrow/PopcornTimeTV#1]
Hello,

Im really glad you are updating PopcornTime TV
![screen shot 2017-10-26 at 12 33 59](https://user-images.githubusercontent.com/19361341/32048592-4bebf166-ba4a-11e7-8771-13e8e1ef8d3a.png)

Compiled and working on my 4k,
I did get a few issue warnings.
Thank you.

**Comment by Kinglilrowrow** [comment]
Yeah I'll be working on fixing some of the warnings over the next few weeks, as I'm in the process of of updating the code base for Swift 4.
