### ISSUE TITLE
ipa?

### ISSUE THREAD

**Issue by tomto147** [Kinglilrowrow/PopcornTimeTV#11]
I am unable to sign the project because of some provisioning problems. Would you be so kind to compile ipa file for me to resign manually? Thanks

**Comment by Kinglilrowrow** [comment]
I don't provide IPA's due to my signing identity being revealed if it where to be unpackaged. 

I'm rewriting the app from ground up right now so will not be updating this repo instead pushing to the new one when it's ready.

**Comment by tomto147** [comment]
Understand. 
I was able to sing and install the app on my iPhone. BTW search option crashes the app. But I was not able to install the same app on my AppleTV. I get an error message “device type missmatch requires ios 11.1 iphone ipod ipad against AppleTV”. Can you suggest a sellution for me?
