### ISSUE TITLE
Issues with compiling

### ISSUE THREAD

**Issue by kamikazecase** [Kinglilrowrow/PopcornTimeTV#13]
![screen shot 2017-12-05 at 7 45 58 pm](https://user-images.githubusercontent.com/34289818/33638597-f186d752-d9f4-11e7-920c-24eee02763f6.png)
Hello! Just a quick question for you. I have compiled this successfully, but when I click run I get a code signing error back. Do I have to have a paid developer account to sign this? I'm using a free personal developer account right now. Thanks for your help!

**Comment by Kinglilrowrow** [comment]
Change the identifiers to whatever you want then re-run the build. Xcode should fix it for you.
