### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by PencilNotPen** [Kinglilrowrow/PopcornTimeTV#15]
Good work on PopcornTime 4.2, I've got it running on an ATV 4 and 4K on tvOS 11.x. Had to change some of your bundle IDs which were left in, as well as deployment target OS (tvOS 11.0/1 instead of 11.2), but all working now. It also builds with Automatic dark/light on which is neat.

There are a few UI bugs I wanted to tell you about, here's a link to a few pictures which illustrate the bugs:

https://www.dropbox.com/sh/4g1h881ocmeclcs/AABYYhCKRH85S5ZyXUw7zZEVa?dl=0

Bug 1: When going from the movie/tv show thumbnails view to a specific movie/tv show view, and then back to the thumbnail view, the layout changes to only three thumbs wide, instead of the whole screen. Picture 1 (see link) shows the correct layout, Picture 2 shows the layout after selecting a movie and then going back again.

Bug 2: When selecting a single movie, the loading page is not fully blurred, it is cut off at the top and bottom (where the UI from the previous page was?) Picture 3 shows this. In PopcornTime 3.1.3, this did not happen, and Picture 5 shows the correct fully blurred screen.

Bug 3: Probably related to Bug 2, when selecting a single movie/tv show, the bottom of the screen is again cut off (in the viewers also watched area). This can be seen in Picture 4. In PopcornTime 3.1.3, the correct layout extended all the way to the bottom of the screen, as seen in Picture 6.

Hope these help to show the issues. If you want help making an unsigned IPA to add to releases, it is possible to make one, let me know. Can't wait for 4K streaming to come along!

Cheers

**Comment by anonymouse1989** [comment]
Hi! Can you help me to compile this? I cant seem to find anyone that can help me.

**Comment by tomto147** [comment]
@PencilNotPen can you tell me what did you change in bundle IDs? I am not able to complie this for ATV. I only sucseeded on iOS. When trying to complie for TVos I am getting bundle IDs incompatibility.

**Comment by anonymouse1989** [comment]
Make sure to clean your build first. What error are you having? Make sure your topshelf and bundle id has the same parent id.

eg:

Com.yourname.popcorntime.tvos
Com.yourname.popcorntime.TopShelf
