### ISSUE TITLE
Popcorntime crashes on ios when clicking search tab.

### ISSUE THREAD

**Issue by anonymouse1989** [Kinglilrowrow/PopcornTimeTV#18]
Managed to get it working for both ios and tvos, tvos is working great, while the ios version crashes when clicking search tab.

**Comment by jublaustein** [comment]
I noticed it also crashes when opening a external magnet link, via safari. It will open the stream but crash and close the playback window at about 5 seconds.
Overall it’s a great experience on both iOS and tvOS!

**Comment by Kinglilrowrow** [comment]
Version 5.0.0 will be available shortly after iOS and tvOS 12 release publicly.
