### ISSUE TITLE
4.0.1 quits

### ISSUE THREAD

**Issue by sqig** [Kinglilrowrow/PopcornTimeTV#3]
Hello,
4.0.1.quits for me just after I select a movie.
I also noticed that download had gone.
I got some issues when compiling but maybe just me.

Thank you

![screen shot 2017-10-30 at 11 25 52](https://user-images.githubusercontent.com/19361341/32166272-9515ebe4-bd65-11e7-8314-1c7d205c2f60.png)

**Comment by Kinglilrowrow** [comment]
Whats version of the Xcode IDE are you using?

**Comment by sqig** [comment]
I will try again.
Thank you.
![screen shot 2017-10-30 at 17 37 03](https://user-images.githubusercontent.com/19361341/32183285-31dee088-bd99-11e7-80a5-58e7703a0c70.png)

**Comment by Kinglilrowrow** [comment]
Fixed with above commit, thanks.

**Comment by sqig** [comment]
Thank you.
I will have another go in the morning.

**Comment by Kinglilrowrow** [comment]
Okay, It's fixed my end but I'll wait on your report before closing this issue.

**Comment by sqig** [comment]
Working well here.
Well done .
Thank you.

**Comment by Kinglilrowrow** [comment]
Awesome, thanks.
