### ISSUE TITLE
search problems

### ISSUE THREAD

**Issue by doctor2018** [Kinglilrowrow/PopcornTimeTV#4]
i detect problems trying searching movies, series and tv shows:

In popcorntime for apple tv ,when i go to search tab it only search for movies, there is no option to search for series and tv shows. (apple tv 4k)
In popcorntime for ios, when i go to search tab the program suddenly close. (ipad pro)

Some times when i download series or episodies, the popcorntime for apple tv suddenly closes. (apple tv 4k)

**Comment by Kinglilrowrow** [comment]
I don't fully support the iOS version yet, i'm still mainly focused on the tvOS version but I will look into it as I have not ran into this issue on my iPad Pro 10.5 running iOS 11.1 GM.

The search issue on tvOS i'll get working on tonight.

As always when compiling please use the latest version of the Xcode IDE and latest tvOS/iOS version which is now tvOS and iOS 11.1 and Xcode 9.1 respectively. 

Thanks.

**Comment by doctor2018** [comment]
sometimes the movies and series do not load well

**Comment by doctor2018** [comment]
thank you

**Comment by Kinglilrowrow** [comment]
Check, https://github.com/Kinglilrowrow/PopcornTimeTV/commit/6174550a662d5ec9b64e0f2170c8d913069467e7

And revert/add as you see fit.
