### ISSUE TITLE
iOS App Crashes on iPhone X 11.1 When Pressing Search On Botton Nav Bar

### ISSUE THREAD

**Issue by freddieerg** [Kinglilrowrow/PopcornTimeTV#4]
<img width="1019" alt="screen shot 2017-11-07 at 13 40 28" src="https://user-images.githubusercontent.com/14265430/32496475-42484d78-c3c1-11e7-8ebd-8cf784f46b30.png">

**Comment by Kinglilrowrow** [comment]
Thanks for the feedback, I'm fully aware of this one though. 

Check: https://github.com/Kinglilrowrow/PopcornTimeTV/releases

For known issues in the current release. 

Thanks.

**Comment by freddieerg** [comment]
Ok great! Sorry for not checking, didn't see there was a known issue tracker!

**Comment by Kinglilrowrow** [comment]
That's fine, if you find anything else please feel free to report it. 

I'm in need of iPhone X testers too as I got the 8 Plus instead this year and Xcode isn't much help.

**Comment by aminmahdi** [comment]
did you fix it ?
