### ISSUE TITLE
Player issue

### ISSUE THREAD

**Issue by soygalla** [Kinglilrowrow/PopcornTimeTV#7]
Hi, I've noticed an issue while playing content the app stops responding to the remote, I can't pause/play, can't go back; The only thing I can do is exiting the app and restart it so I can use it again. This does not happens all the time, just from time to time. Hope you can't look into it. I have the Apple TV 4.

Thank you  for keeping this client updated👍

**Comment by Kinglilrowrow** [comment]
Thanks for the feedback, as I'm in the process of rewriting this client the current bugs won't get seen to. 

The rewrite of this app will be out at the beginning of the year and all new bugs will be tracked then.
