### ISSUE TITLE
Subtitles movies Arabic language is not good never

### ISSUE THREAD

**Issue by ADMNTK** [Kinglilrowrow/PopcornTimeTV#8]
Hi

Subtitles movies Arabic language is not good never

1- Movie subtitles untidy.
2- Movie subtitles disappear sometimes.
3- Some Movies, No subtitles.

The best solution to this problem is to put subtitles for movies manually.
After running, select subtitles to the movie manually from the website open subtitle.

Thank You!

**Comment by Kinglilrowrow** [comment]
Thanks for the feedback, as I'm in the process of rewriting this client the current bugs won't get seen to.

The rewrite of this app will be out at the beginning of the year and all new bugs will be tracked then.
